apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
    role: queue
  name: redis-db
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: redis
    role: queue